// Generated by Rcpp::compileAttributes()
// Do not edit by hand

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_fastpam
List cpp_fastpam(NumericVector rdist, int n, int k, int maxiter, std::string initializer, double fasttol, int seed);
RcppExport SEXP _isopam_cpp_fastpam(SEXP rdistSEXP, SEXP nSEXP, SEXP kSEXP, SEXP maxiterSEXP, SEXP initializerSEXP, SEXP fasttolSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rdist(rdistSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< std::string >::type initializer(initializerSEXP);
    Rcpp::traits::input_parameter< double >::type fasttol(fasttolSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fastpam(rdist, n, k, maxiter, initializer, fasttol, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_isopam_cpp_fastpam", (DL_FUNC) &_isopam_cpp_fastpam, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_isopam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
