# Generated by Rcpp::compileAttributes()
# Do not edit by hand

#' @useDynLib isopam, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' FastPAM clustering
#' 
#' @param rdist The distance matrix (lower triangular vector)
#' @param n The number of observations
#' @param k The number of clusters
#' @param maxiter Maximum iterations (default: 0)
#' @param initializer "BUILD" or "LAB" (default)
#' @param fasttol Fast swap tolerance (default: 1.0)
#' @param seed Random seed (default: 123456789)
#' @return A list with cost, medoids, and assignment
#' @keywords internal
cpp_fastpam <- function(rdist, n, k, maxiter = 0L, initializer = "LAB", 
                        fasttol = 1.0, seed = 123456789L) {
    .Call(`_isopam_cpp_fastpam`, rdist, n, k, maxiter, initializer, fasttol, seed)
}
